Pull NLP additions
Onto-Med/top-api pull request #145
Opened 2023-06-26 14:57 UTC by fmatthies

2023-06-27 13:57 UTC, ChristophB requested changes
Please also perform `npx openapi-format schemas/top-api.yml --output schemas/top-api.yml` to reformat the schema file. In future, this step will be added as a GitHub workflow.

2023-06-27 13:57 UTC, ChristophB commented on pom.xml
> +	<version>0.8.0-SNAPSHOT</version>
```suggestion
	<version>0.9.0</version>
```

2023-06-27 13:57 UTC, ChristophB commented on pom.xml
> +	<version>0.8.0-SNAPSHOT</version>
Please also modify the version number in the schema file.

2023-06-27 13:57 UTC, ChristophB commented on schemas/top-api.yml
> +        - name: exemplarOnly
What is the purpose of this query parameter?

2023-06-28 11:06 UTC, ChristophB commented on schemas/top-api.yml
>          - name: gatheringMode
Add a short description. Mention possible values.

2023-06-30 11:17 UTC, fmatthies commented
> Please also perform `npx openapi-format schemas/top-api.yml --output schemas/top-api.yml` to reformat the schema file. In future, this step will be added as a GitHub workflow.

Done, but it didn't change anything.

2023-06-30 11:22 UTC, fmatthies reviewed
applied requested changes

2023-06-30 11:31 UTC, ChristophB approved these changes

2023-06-30 11:39 UTC, merged